FROM ubuntu:20.04 as base

# install python2
RUN \
  DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y build-essential python-dev curl \
  && rm -rf /var/lib/apt/lists/*

# install pip
RUN curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py && python2 get-pip.py

# install requirements
WORKDIR /src
COPY . .
RUN python -m pip install .[tests]
