version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.6
      - test-3.7
      - test-3.8
      - static-code-analysis
      - static-code-analysis-py2

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: sudo pip install .[tests]
  - run:
      name: Test
      command: pytest

jobs:
  test-2.7:
    <<: *defaults
    docker:
      - image: circleci/python:2.7

  test-3.6:
    <<: *defaults
    docker:
      - image: circleci/python:3.6

  test-3.7:
    <<: *defaults
    docker:
      - image: circleci/python:3.7

  test-3.8:
    <<: *defaults
    docker:
      - image: circleci/python:3.8

  static-code-analysis:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install .[tests] black isort mypy types-requests types-mock
      - run:
          name: black
          command: black --check .
      - run:
          name: isort
          command: isort -c .
      - run:
          name: mypy
          command: mypy authalligator_client tests
      - run:
          name: flake8
          command: flake8

  static-code-analysis-py2:
    working_directory: ~/code
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install .[tests]
      - run:
          name: flake8
          command: flake8
